# Generated by Django 2.1.4 on 2018-12-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'todo',
                'verbose_name_plural': 'todos',
                'default_related_name': 'todos',
            },
        ),
    ]
