# Generated by Django 2.1.4 on 2019-01-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190108_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
    ]
