# Generated by Django 2.1.4 on 2019-01-16 10:30

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20190116_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=todos.models.scramble_uploaded_filename),
        ),
    ]
