# Generated by Django 2.1.4 on 2019-01-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20190116_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dateOfBirth',
            field=models.DateField(blank=True),
        ),
    ]
