# Generated by Django 2.1.4 on 2019-01-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_auto_20190117_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
