# Generated by Django 2.1.4 on 2019-01-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_auto_20190117_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
