# Generated by Django 2.1.4 on 2019-02-11 03:33

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_todo_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='taskImage',
            field=models.ImageField(blank=True, null=True, upload_to=todos.models.uploaded_task_image),
        ),
    ]
