# Generated by Django 2.1.4 on 2019-02-14 02:15

from django.db import migrations, models
import django.db.models.deletion
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_todo_taskimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskImage', models.ImageField(blank=True, null=True, upload_to=todos.models.uploaded_task_image)),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='taskImage',
        ),
        migrations.AddField(
            model_name='taskimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.Todo'),
        ),
    ]
